databases:
  - name: notes_demo_api
    databaseName: notes_demo_api
    user: notes_demo_api
    plan: free

services:
  - type: web
    name: notes_demo_api
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes_demo_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false